# K-Space Path Generation
For P3m1 spacegroup, we have high symmetry points defined here. Then if we want to generate a specific path, we would just need to call `path_gen`. 

To do:
1. Add finer mesh of points near Gamma 
2. Write a script to generate the input file. 

In [2]:
import numpy as np

In [3]:
gamma = np.array([0.0, 0.0, 0.0])
A = np.array([0.0, 0.0, 0.5])
H = np.array([1/3, 1/3, 1/2]) 
K = np.array([1/3, 1/3, 0.0])
H2 = np.array([1/3, 1/3, -1/2])
L = np.array([1/2, 0, 1/2]) 
M = np.array([1/2, 0, 0])

In [147]:
def gen_two_points2(x1, x2, num_points = 30):
    """ generates points on a line between two points """
    slope_vector = x2 - x1 
    
    t = np.linspace(0, 1, num_points)
    
    x_data = x1[0] + slope_vector[0] * t 
    y_data = x1[1] + slope_vector[1] * t 
    z_data = x1[2] + slope_vector[2] * t 
    
    return [x_data, y_data, z_data]

def distance(x,y):
    if np.sqrt(np.dot((x-y), (x-y))) < 0.4:
        return 17
    else:
        return 30 
    
def distance2(x,y):
    if np.sqrt(np.dot((x-y), (x-y))) < 0.4:
        return 12
    else:
        return 20

def path_gen(*args):
    num_points = 0
    counter = 0
    for index, arg in enumerate(args):
        counter += 1
        if index == 0:
            continue 
        elif index == 1:
            dis = distance(args[index-1], args[index])
            num_points += dis 
            data = gen_two_points2(args[index-1], args[index], dis)
            for i in range(len(data[0])):
                print("\t" + str(f"{data[0][i]:.10f}") + "\t" + str(f"{data[1][i]:.10f}") + "\t" + str(f"{data[2][i]:.10f}") + "\t 1" ) 
        else:
            dis = distance(args[index-1], args[index])
            num_points += dis 
            data = gen_two_points2(args[index-1], args[index], dis)
            for i in range(1, len(data[0])):
                print("\t" + str(f"{data[0][i]:.10f}") + "\t" + str(f"{data[1][i]:.10f}") + "\t" + str(f"{data[2][i]:.10f}") + "\t 1" ) 
    print(num_points - counter + 2)

    
def is_point(point1, point2):
    """ compares if two points are the same """
    for i in range(len(point1)):
        if point1[i] != point2[i]:
            return False 
    return True 

def path_gen_small(kz, *args):
    """ calculates path for reduced range 
        optimized to have more points near Gamma 
    """
    num_points = 0 
    counter = 0
    for index, arg in enumerate(args):
        counter += 1 
        if index == 0:
            continue 
        elif index == 1: 
            dis = distance(args[index -1], args[index])
            num_points += dis
            
            if is_point(args[index], gamma):    
                num_points += 25
                data1 = gen_two_points2(args[index - 1], args[index - 1] * 0.25, dis)
                data2 = gen_two_points2(args[index - 1] * 0.25, args[index], 25)
                data1[2] += kz
                data2[2] += kz
                for i in range(3):
                    data2[i] = np.delete(data2[i], 0)
                for i in range(len(data1[0])):
                    print("\t" + str(f"{data1[0][i]:.10f}") + "\t" + str(f"{data1[1][i]:.10f}") + "\t" + str(f"{data1[2][i]:.10f}") + "\t 1" )
                for i in range(len(data2[0])):
                    print("\t" + str(f"{data2[0][i]:.10f}") + "\t" + str(f"{data2[1][i]:.10f}") + "\t" + str(f"{data2[2][i]:.10f}") + "\t 1" )
            
            elif is_point(args[index - 1], gamma):
                num_points += 25
                data1 = gen_two_points2(args[index - 1], args[index] * 0.25, 25)
                data2 = gen_two_points2(args[index] * 0.25, args[index], dis)
                data1[2] += kz
                data2[2] += kz
                for i in range(3):
                    data2[i] = np.delete(data2[i], 0)
                for i in range(len(data1[0])):
                    print("\t" + str(f"{data1[0][i]:.10f}") + "\t" + str(f"{data1[1][i]:.10f}") + "\t" + str(f"{data1[2][i]:.10f}") + "\t 1" )
                for i in range(len(data2[0])):
                    print("\t" + str(f"{data2[0][i]:.10f}") + "\t" + str(f"{data2[1][i]:.10f}") + "\t" + str(f"{data2[2][i]:.10f}") + "\t 1" )
        
        else:
            dis = distance(args[index -1], args[index])
            num_points += dis
            
            if is_point(args[index], gamma):    
                num_points += 25
                data1 = gen_two_points2(args[index - 1], args[index - 1] * 0.25, dis)
                data2 = gen_two_points2(args[index - 1] * 0.25, args[index], 25)
                data1[2] += kz
                data2[2] += kz
                for i in range(3):
                    data2[i] = np.delete(data2[i], 0)
                for i in range(1, len(data1[0])):
                    print("\t" + str(f"{data1[0][i]:.10f}") + "\t" + str(f"{data1[1][i]:.10f}") + "\t" + str(f"{data1[2][i]:.10f}") + "\t 1" )
                for i in range(len(data2[0])):
                    print("\t" + str(f"{data2[0][i]:.10f}") + "\t" + str(f"{data2[1][i]:.10f}") + "\t" + str(f"{data2[2][i]:.10f}") + "\t 1" )
            
            elif is_point(args[index - 1], gamma):
                num_points += 25
                data1 = gen_two_points2(args[index - 1], args[index] * 0.25, 25)
                data2 = gen_two_points2(args[index] * 0.25, args[index], dis)
                data1[2] += kz
                data2[2] += kz
                for i in range(3):
                    data2[i] = np.delete(data2[i], 0)
                for i in range(1, len(data1[0])):
                    print("\t" + str(f"{data1[0][i]:.10f}") + "\t" + str(f"{data1[1][i]:.10f}") + "\t" + str(f"{data1[2][i]:.10f}") + "\t 1" )
                for i in range(len(data2[0])):
                    print("\t" + str(f"{data2[0][i]:.10f}") + "\t" + str(f"{data2[1][i]:.10f}") + "\t" + str(f"{data2[2][i]:.10f}") + "\t 1" )
    
    print(num_points - counter)

In [149]:
kz = 0.035
path_gen_small(kz, K, gamma, -1* K)

	0.3333333333	0.3333333333	0.0350000000	 1
	0.3247126437	0.3247126437	0.0350000000	 1
	0.3160919540	0.3160919540	0.0350000000	 1
	0.3074712644	0.3074712644	0.0350000000	 1
	0.2988505747	0.2988505747	0.0350000000	 1
	0.2902298851	0.2902298851	0.0350000000	 1
	0.2816091954	0.2816091954	0.0350000000	 1
	0.2729885057	0.2729885057	0.0350000000	 1
	0.2643678161	0.2643678161	0.0350000000	 1
	0.2557471264	0.2557471264	0.0350000000	 1
	0.2471264368	0.2471264368	0.0350000000	 1
	0.2385057471	0.2385057471	0.0350000000	 1
	0.2298850575	0.2298850575	0.0350000000	 1
	0.2212643678	0.2212643678	0.0350000000	 1
	0.2126436782	0.2126436782	0.0350000000	 1
	0.2040229885	0.2040229885	0.0350000000	 1
	0.1954022989	0.1954022989	0.0350000000	 1
	0.1867816092	0.1867816092	0.0350000000	 1
	0.1781609195	0.1781609195	0.0350000000	 1
	0.1695402299	0.1695402299	0.0350000000	 1
	0.1609195402	0.1609195402	0.0350000000	 1
	0.1522988506	0.1522988506	0.0350000000	 1
	0.1436781609	0.1436781609	0.0350000000	 1
	0.13505747

In [131]:
kz = 0.0045
path_gen_small(kz, K + kz, gamma + kz, -1 * K + kz)

	0.3378333333	0.3378333333	0.0045000000	 1
	0.3273488506	0.3273488506	0.0043603448	 1
	0.3168643678	0.3168643678	0.0042206897	 1
	0.3063798851	0.3063798851	0.0040810345	 1
	0.2958954023	0.2958954023	0.0039413793	 1
	0.2854109195	0.2854109195	0.0038017241	 1
	0.2749264368	0.2749264368	0.0036620690	 1
	0.2644419540	0.2644419540	0.0035224138	 1
	0.2539574713	0.2539574713	0.0033827586	 1
	0.2434729885	0.2434729885	0.0032431034	 1
	0.2329885057	0.2329885057	0.0031034483	 1
	0.2225040230	0.2225040230	0.0029637931	 1
	0.2120195402	0.2120195402	0.0028241379	 1
	0.2015350575	0.2015350575	0.0026844828	 1
	0.1910505747	0.1910505747	0.0025448276	 1
	0.1805660920	0.1805660920	0.0024051724	 1
	0.1700816092	0.1700816092	0.0022655172	 1
	0.1595971264	0.1595971264	0.0021258621	 1
	0.1491126437	0.1491126437	0.0019862069	 1
	0.1386281609	0.1386281609	0.0018465517	 1
	0.1281436782	0.1281436782	0.0017068966	 1
	0.1176591954	0.1176591954	0.0015672414	 1
	0.1071747126	0.1071747126	0.0014275862	 1
	0.09669022

In [132]:
kz = 0
path_gen_small(kz, K + kz, gamma + kz, -1 * K + kz)

	0.3333333333	0.3333333333	0.0000000000	 1
	0.3229885057	0.3229885057	0.0000000000	 1
	0.3126436782	0.3126436782	0.0000000000	 1
	0.3022988506	0.3022988506	0.0000000000	 1
	0.2919540230	0.2919540230	0.0000000000	 1
	0.2816091954	0.2816091954	0.0000000000	 1
	0.2712643678	0.2712643678	0.0000000000	 1
	0.2609195402	0.2609195402	0.0000000000	 1
	0.2505747126	0.2505747126	0.0000000000	 1
	0.2402298851	0.2402298851	0.0000000000	 1
	0.2298850575	0.2298850575	0.0000000000	 1
	0.2195402299	0.2195402299	0.0000000000	 1
	0.2091954023	0.2091954023	0.0000000000	 1
	0.1988505747	0.1988505747	0.0000000000	 1
	0.1885057471	0.1885057471	0.0000000000	 1
	0.1781609195	0.1781609195	0.0000000000	 1
	0.1678160920	0.1678160920	0.0000000000	 1
	0.1574712644	0.1574712644	0.0000000000	 1
	0.1471264368	0.1471264368	0.0000000000	 1
	0.1367816092	0.1367816092	0.0000000000	 1
	0.1264367816	0.1264367816	0.0000000000	 1
	0.1160919540	0.1160919540	0.0000000000	 1
	0.1057471264	0.1057471264	0.0000000000	 1
	0.09540229

In [56]:
gamma * 0.9

array([0., 0., 0.])

In [55]:
gen_two_points2(gamma * 0.9, gamma * 0.9, 30)

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [39]:
M == gamma

array([False,  True,  True])

In [14]:
gen_two_points2(gamma, M * 0.1, 10)

[array([0.        , 0.00555556, 0.01111111, 0.01666667, 0.02222222,
        0.02777778, 0.03333333, 0.03888889, 0.04444444, 0.05      ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [27]:
test = gen_two_points2(M*0.1, M, 30)
test[0] = np.delete(test[0], 0)
test[1] = np.delete(test[1], 0)
test[2] = np.delete(test[2], 0)
test

[array([0.06551724, 0.08103448, 0.09655172, 0.11206897, 0.12758621,
        0.14310345, 0.15862069, 0.17413793, 0.18965517, 0.20517241,
        0.22068966, 0.2362069 , 0.25172414, 0.26724138, 0.28275862,
        0.29827586, 0.3137931 , 0.32931034, 0.34482759, 0.36034483,
        0.37586207, 0.39137931, 0.40689655, 0.42241379, 0.43793103,
        0.45344828, 0.46896552, 0.48448276, 0.5       ]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [31]:
[[0,0,0], [1,1,1]] + [[0,0,0], [1,1,1]]

[[0, 0, 0], [1, 1, 1], [0, 0, 0], [1, 1, 1]]

In [24]:
np.delete(test, [0][0]).shape

(89,)

In [25]:
test.shape

AttributeError: 'list' object has no attribute 'shape'

In [12]:
path_gen(gamma, M, gamma)

	0.0000000000	0.0000000000	0.0000000000	 1
	0.0172413793	0.0000000000	0.0000000000	 1
	0.0344827586	0.0000000000	0.0000000000	 1
	0.0517241379	0.0000000000	0.0000000000	 1
	0.0689655172	0.0000000000	0.0000000000	 1
	0.0862068966	0.0000000000	0.0000000000	 1
	0.1034482759	0.0000000000	0.0000000000	 1
	0.1206896552	0.0000000000	0.0000000000	 1
	0.1379310345	0.0000000000	0.0000000000	 1
	0.1551724138	0.0000000000	0.0000000000	 1
	0.1724137931	0.0000000000	0.0000000000	 1
	0.1896551724	0.0000000000	0.0000000000	 1
	0.2068965517	0.0000000000	0.0000000000	 1
	0.2241379310	0.0000000000	0.0000000000	 1
	0.2413793103	0.0000000000	0.0000000000	 1
	0.2586206897	0.0000000000	0.0000000000	 1
	0.2758620690	0.0000000000	0.0000000000	 1
	0.2931034483	0.0000000000	0.0000000000	 1
	0.3103448276	0.0000000000	0.0000000000	 1
	0.3275862069	0.0000000000	0.0000000000	 1
	0.3448275862	0.0000000000	0.0000000000	 1
	0.3620689655	0.0000000000	0.0000000000	 1
	0.3793103448	0.0000000000	0.0000000000	 1
	0.39655172

In [99]:
path_gen(M, gamma, -1*M)

	0.5000000000	0.0000000000	0.0000000000	 1
	0.4827586207	0.0000000000	0.0000000000	 1
	0.4655172414	0.0000000000	0.0000000000	 1
	0.4482758621	0.0000000000	0.0000000000	 1
	0.4310344828	0.0000000000	0.0000000000	 1
	0.4137931034	0.0000000000	0.0000000000	 1
	0.3965517241	0.0000000000	0.0000000000	 1
	0.3793103448	0.0000000000	0.0000000000	 1
	0.3620689655	0.0000000000	0.0000000000	 1
	0.3448275862	0.0000000000	0.0000000000	 1
	0.3275862069	0.0000000000	0.0000000000	 1
	0.3103448276	0.0000000000	0.0000000000	 1
	0.2931034483	0.0000000000	0.0000000000	 1
	0.2758620690	0.0000000000	0.0000000000	 1
	0.2586206897	0.0000000000	0.0000000000	 1
	0.2413793103	0.0000000000	0.0000000000	 1
	0.2241379310	0.0000000000	0.0000000000	 1
	0.2068965517	0.0000000000	0.0000000000	 1
	0.1896551724	0.0000000000	0.0000000000	 1
	0.1724137931	0.0000000000	0.0000000000	 1
	0.1551724138	0.0000000000	0.0000000000	 1
	0.1379310345	0.0000000000	0.0000000000	 1
	0.1206896552	0.0000000000	0.0000000000	 1
	0.10344827

In [6]:
kz = [0.0, 0.0, 0.05]
path_gen(K + kz, gamma + kz, -1*K + kz)

	0.3333333333	0.3333333333	0.0500000000	 1
	0.3218390805	0.3218390805	0.0500000000	 1
	0.3103448276	0.3103448276	0.0500000000	 1
	0.2988505747	0.2988505747	0.0500000000	 1
	0.2873563218	0.2873563218	0.0500000000	 1
	0.2758620690	0.2758620690	0.0500000000	 1
	0.2643678161	0.2643678161	0.0500000000	 1
	0.2528735632	0.2528735632	0.0500000000	 1
	0.2413793103	0.2413793103	0.0500000000	 1
	0.2298850575	0.2298850575	0.0500000000	 1
	0.2183908046	0.2183908046	0.0500000000	 1
	0.2068965517	0.2068965517	0.0500000000	 1
	0.1954022989	0.1954022989	0.0500000000	 1
	0.1839080460	0.1839080460	0.0500000000	 1
	0.1724137931	0.1724137931	0.0500000000	 1
	0.1609195402	0.1609195402	0.0500000000	 1
	0.1494252874	0.1494252874	0.0500000000	 1
	0.1379310345	0.1379310345	0.0500000000	 1
	0.1264367816	0.1264367816	0.0500000000	 1
	0.1149425287	0.1149425287	0.0500000000	 1
	0.1034482759	0.1034482759	0.0500000000	 1
	0.0919540230	0.0919540230	0.0500000000	 1
	0.0804597701	0.0804597701	0.0500000000	 1
	0.06896551

# Input File Generation